server.port=9090
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DATASOURCE_URL:jdbc:mysql://localhost:3306/db_plazoleta?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${USER_DB:root}
spring.datasource.password=${PASSWORD_DB:12345}
spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=never

#logging.level.com.reto.plazoleta.infraestructure.entrypoint.*=TRACE

base.url.micro.user=${MICRO_USER_URL:http://localhost:8090/user-micro/}
base.url.micro.messenger.service=${MICRO_MESSENGER_SERVICE_URL:http://localhost:9280/messenger-service/}

access.token.secret=${ACCESS_TOKEN_SECRET:8y/B?E(G+KbPeShVmYq3t6w9z$C&F)J@}