server.port=9090
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DATASOURCE_URL:jdbc:mysql://localhost:3306/db_plazoleta?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${USER_DB:root}
spring.datasource.password=${PASSWORD_DB:12345}
spring.jpa.hibernate.ddl-auto=${MODE_DDL_DB:update}
server.error.include-stacktrace=never

#logging.level.com.reto.plazoleta.infraestructure.entrypoint.*=TRACE
#logging.level.org.springframework.cache=TRACE

base.url.micro.user=${MICRO_USER_URL:http://localhost:8090/user-micro/}
base.url.micro.messenger.service=${MICRO_MESSENGER_SERVICE_URL:http://localhost:9280/messenger-service/}

access.token.secret=${ACCESS_TOKEN_SECRET:8y/B?E(G+KbPeShVmYq3t6w9z$C&F)J@}

spring.cache.redis.time-to-live=${CACHE_EXPIRATION_TIME_MS:600000ms}
spring.cache.type=redis
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}
spring.redis.timeout=10000ms
spring.redis.lettuce.pool.max-active=20
spring.redis.lettuce.pool.max-idle=20
spring.redis.lettuce.pool.min-idle=2
spring.redis.lettuce.pool.max-wait=5000ms

