# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  displayName: 'Gradlew Build'
  inputs:
    tasks: 'build'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    Dockerfile: deployment/Dockerfile

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: 'docker_hub_account'
    repository: 'jaider18/plazoleta'
    Dockerfile: deployment/Dockerfile
